name: vader_cli_example
description: Example of vader_cli.
version: 1.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  vader_cli:
    path: ../

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
