name: vader_cli
description: Vader package for build cli programs.
version: 1.0.0-dev.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  args: ^2.6.0
  cli_menu: ^0.4.0+1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
