name: vader_cli
description: Vader package for build cli programs.
repository: https://github.com/mjablecnik/vader_framework/tree/master/core/vader_cli
resolution: workspace
version: 1.0.0-dev.2

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  args: ^2.6.0
  path: ^1.9.1
  cli_menu: ^0.4.0+1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
