name: vader_cli
description: Vader package for build cli programs.
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  args: ^2.6.0
  cli_menu: ^0.4.0+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
