name: vader_console_example
description: Example of vader_console.
version: 1.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  vader_console:
    path: ../

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
