name: vader_framework
publish_to: none
environment:
  sdk: ^3.7.0
workspace:
  - cli/code_builder
  - cli/design_builder
  - cli/vader_manager
  - core/vader_app
  #- core/vader_app_info
  - core/vader_cli
  - core/vader_core
  - core/vader_design
  #- example_design
  #- example_project
