name: vader_manager
description: CLI Manager for Vader framework.
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  yaml: ^3.1.1
  vader_cli:
    path: ../../core/vader_cli

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
