name: vader_manager
description: CLI Manager for Vader framework.
resolution: workspace
publish_to: none
version: 1.0.0-dev.1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  yaml: ^3.1.1
  vader_cli:
    path: ../../core/vader_cli

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
