name: vader_design
description: Helper package for design packages
resolution: workspace
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  color_palette_plus: ^1.0.0


dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
