name: vader_design
description: Helper package for design packages
repository: https://github.com/mjablecnik/vader_framework/tree/master/core/vader_design
resolution: workspace
version: 0.2.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  stack_trace: ^1.12.1
  color_palette_plus: ^1.0.0


dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
