name: design_builder
description: Builder for build directory structure in vader design package.
version: 1.0.0-dev.2

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  dart_style: ^3.0.1
  recase: ^4.1.0
  vader_cli:
    path: ../../core/vader_cli

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.14
