name: design_builder
description: Builder for build directory structure in vader design package.
resolution: workspace
publish_to: none
version: 1.0.0-dev.2

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  dart_style: ^3.0.1
  recase: ^4.1.0
  vader_console:
    path: ../../core/vader_console

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
