name: vader_core
description: Framework for simplify development of Flutter apps
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  # Common:
  mocktail: ^1.0.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mek_data_class: ^1.4.0

  # Repository:
  dio: ^5.8.0+1
  retry: ^3.1.2
  hive_ce: ^2.10.1
  auto_injector: ^2.0.5

  # Logger:
  talker: ^4.6.7
  talker_dio_logger: ^4.6.7


dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
