name: vader
description: Project contain common project tools
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Common:
  mocktail: 1.0.4
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  mek_data_class: 1.4.0

  # Repository:
  dio: 5.5.0+1
  auto_injector: 2.0.5
  flutter_secure_storage: 9.2.2
  internet_connection_checker: 1.0.0+1

  # State Manager:
  bloc: 8.1.4
  flutter_bloc: 8.1.6

  # Logger:
  talker: <=4.1.2             # Upgrade to higher version only after upgrade Java SDK to version 17
  talker_dio_logger: <=4.1.2  # Upgrade to higher version only after upgrade Java SDK to version 17

  # Connection:
  #flutter_offline: 3.0.1
  #internet_connection_checker: 1.0.0+1

dev_dependencies:
  lints: 4.0.0
  test: 1.24.0
