name: code_builder
description: Program for generating some parts of code during development.
version: 0.1.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  mason: ^0.1.0
  vader_cli:
    path: ../../core/vader_cli

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
