name: vader_app_info
description: Give you info about package and device
#resolution: workspace
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  mocktail: 1.0.4
  #device_info_plus: <=9.1.2      # Upgrade to higher version only after upgrade Java SDK to version 17
  package_info_plus: <=4.0.1     # Upgrade to higher version only after upgrade Java SDK to version 17
  flutter_secure_storage: 9.2.2
  mobile_device_identifier: 0.0.2
  android_device_id_generator: 0.1.1

dev_dependencies:
  lints: 5.1.1
  test: 1.25.15
